### ISSUE TITLE
Hello, Dr.Yang. I don't know how to download the HDFS dataset.

### ISSUE THREAD

**Issue by EasonLee2021** [YangLin-George/PLELog#1]
I am instersted in your paper, but I don't know how to download the HDFS dataset.
Would  you like to tell me how to download the HDFS dataset?

**Comment by YangLin-George** [comment]
Hi @EasonLee2021 , HDFS dataset is available in [loghub repo](https://github.com/logpai/loghub), you can follow the instructions of applying their open-source datasets to get HDFS and other amazing log data. 

Please feel free to email me directly if you have further questions. My email address is linyang@tju.edu.cn
