### ISSUE TITLE
How to get templates in parse_by_Official() function of class HDFSLoader

### ISSUE THREAD

**Issue by tunglambk** [YangLin-George/PLELog#11]
Hi Dr. Yang,

Can you guide me on how to get the templates like this? Thank you so much.

```
class HDFSLoader(BasicDataLoader):

    ...

    def parse_by_Official(self):
        self._restore()
        templates = [
            "Adding an already existing block (.*)",
            "(.*)Verification succeeded for (.*)",
            "(.*) Served block (.*) to (.*)",
            "(.*):Got exception while serving (.*) to (.*):(.*)",
            "Receiving block (.*) src: (.*) dest: (.*)",
            "Received block (.*) src: (.*) dest: (.*) of size ([-]?[0-9]+)",
            "writeBlock (.*) received exception (.*)",
            "PacketResponder ([-]?[0-9]+) for block (.*) Interrupted\.",
            "Received block (.*) of size ([-]?[0-9]+) from (.*)",
            "PacketResponder (.*) ([-]?[0-9]+) Exception (.*)",
            "PacketResponder ([-]?[0-9]+) for block (.*) terminating",
            "(.*):Exception writing block (.*) to mirror (.*)(.*)",
            "Receiving empty packet for block (.*)",
            "Exception in receiveBlock for block (.*) (.*)",
            "Changing block file offset of block (.*) from ([-]?[0-9]+) to ([-]?[0-9]+) meta file offset to ([-]?[0-9]+)",
            "(.*):Transmitted block (.*) to (.*)",
            "(.*):Failed to transfer (.*) to (.*) got (.*)",
            "(.*) Starting thread to transfer block (.*) to (.*)",
            "Reopen Block (.*)",
            "Unexpected error trying to delete block (.*)\. BlockInfo not found in volumeMap\.",
            "Deleting block (.*) file (.*)",
            "BLOCK\* NameSystem\.allocateBlock: (.*)\. (.*)",
            "BLOCK\* NameSystem\.delete: (.*) is added to invalidSet of (.*)",
            "BLOCK\* Removing block (.*) from neededReplications as it does not belong to any file\.",
            "BLOCK\* ask (.*) to replicate (.*) to (.*)",
            "BLOCK\* NameSystem\.addStoredBlock: blockMap updated: (.*) is added to (.*) size ([-]?[0-9]+)",
            "BLOCK\* NameSystem\.addStoredBlock: Redundant addStoredBlock request received for (.*) on (.*) size ([-]?[0-9]+)",
            "BLOCK\* NameSystem\.addStoredBlock: addStoredBlock request received for (.*) on (.*) size ([-]?[0-9]+) But it does not belong to any file\.",
            "PendingReplicationMonitor timed out block (.*)"
        ]
```

**Comment by YangLin-George** [comment]
Hi @tunglambk,
Sure, its my pleasure! 

Such "ground truth" of HDFS log messages are downloaded from the [homepage of Prof. Wei Xu](http://people.iiis.tsinghua.edu.cn/~weixu/sospdata.html). And we manually moved it into the python project.

According to our experiences with log parsers, I think it is safe to say that those were **manually written** or  **extracted from the source code** of the target system. Log parsers are highly likely to introduce noises.

Hope this will help, if anything, feel free to comment and I am happy to answer :P

**Comment by tunglambk** [comment]
Hi Dr.@YangLin-George ,

Thank you so much for your enthusiastic support.

From your explanation, I understand that if we can extract the log templates from the source code, we should use them like the *parse_by_Official()* function to avoid noise from the log parser. Otherwise, we can use IBM Drain3 to parse logs like the *parse_by_IBM()* function. Is this right?

**Comment by YangLin-George** [comment]
In my opinion, while doing research, log parsing seems necessary. For example, the widely used BGL dataset does not have such a "ground truth" like HDFS.

However, while you are using an anomaly detection approach in industry, if the real templates are available, its better to use them directly.

**Comment by tunglambk** [comment]
Hi Dr. @YangLin-George,

Yeah, I understood. Besides, I have one more question.

> For example, the widely used BGL dataset does not have such a "ground truth" like HDFS.

The *parse_by_Official()* function of the *BGLLoader* class also has templates like *HDFSLoader*. How do you extract it? Thank you so much.

**Comment by YangLin-George** [comment]
Those were written based on the tempaletes generated by Drain. We tried to study the impact of parsing and prepared those.

**Comment by tunglambk** [comment]
Thank you so much for your support and great work, Dr. @YangLin-George, I close this issue here.
