### ISSUE TITLE
Why using FastICA for reducing dimensionality?

### ISSUE THREAD

**Issue by tunglambk** [YangLin-George/PLELog#12]
Hi Dr. @YangLin-George,

Why did you use FastICA for reducing dimensionality but not PCA? In practice, I see that PCA is more popular for dimension reduction and FastICA for separating superimposed signals.

Thank you.

**Comment by YangLin-George** [comment]
Hi @tunglambk,

There is no particular reason why it has to be FastICA, just a choice. Using dimension reduction algorithm is only for accelerating the hdbscan process. 

You can try any other options as long as you see fit.

**Comment by tunglambk** [comment]
Thank you for your comment, Dr. @YangLin-George.
