### ISSUE TITLE
Some problems with the requirements.txt

### ISSUE THREAD

**Issue by tywofxd** [YangLin-George/PLELog#16]
Hello! Thanks for such a great sharing.
I configured my virtual env based on the provided requirements.txt using pip, but some error occured.
1. After the establishment of the virtual env, I started to run the project. The first error occured was: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject.
I searched for solutions, and finally this one worked for me. https://github.com/scikit-learn-contrib/hdbscan/issues/457

I did some experiments, but found that this seems to be a problem with the hdbscan package itself, and has nothing to do with the version of numpy.
If you used the command pip install hdbscan to install the hdbscan package in your virtual environment, please uninstall it, and then try to use the command conda install -c conda-forge hdbscan to reinstall hdbscan.

2. I used the above command to install hdbscan==0.8.27, but then I got the second error: TypeError: __init__() got an unexpected keyword argument 'cachedir'. This solution helped me: https://stackoverflow.com/questions/73830225/init-got-an-unexpected-keyword-argument-cachedir-when-importing-top2vec
I installed hdbscan==0.8.29 using conda, and then everything worked fine.

I put an issue here just want to help anyone who want to establish the env for your code.
Thanks again for your great work.

**Comment by YangLin-George** [comment]
Thanks for your great effort and valuable advice, I'll add this issue into readme.
