### ISSUE TITLE
Question of Preparation Step 4

### ISSUE THREAD

**Issue by zhaochenchen4** [YangLin-George/PLELog#24]
**Step 4:** Run `approaches/PLELog.py` (make sure it has proper parameters).
<img width="855" alt="微信图片_20240722211312" src="https://github.com/user-attachments/assets/e1652824-e3bf-4b30-8b63-49efe3ae610c">
I got this error in the fourth step, can you help me take a look

**Comment by LeonYang95** [comment]
May I have your detailed environment info?

Plus, it seems like there is something wrong with  the hdbscan package, perhaps you should checkout the latest instructions about it. In addition to that, we have prepared a docker image for PLELog, you can pull that image and try again. You can find the docker image in [Issue#22](https://github.com/LeonYang95/PLELog/issues/22)

**Comment by zhaochenchen4** [comment]
ok,This is my environment info
<img width="554" alt="880c1b355f33b03dd441130afa83b67" src="https://github.com/user-attachments/assets/f6d878fa-1d08-4317-b0de-4234b0ace25d">
<img width="563" alt="ad454e844eb3233a834ff9c0337513f" src="https://github.com/user-attachments/assets/59c101a3-7d21-46c2-b6b3-b4892096e812">
<img width="554" alt="ae6fe5c789a263fa21e625c984020ac" src="https://github.com/user-attachments/assets/995c1396-0af2-4efa-bccc-e0ecd8b81eab">

**Comment by LeonYang95** [comment]
Perhaps try to install the packages without specifying the version?
