### ISSUE TITLE
Run Drain.py to extract templates parameter Settings

### ISSUE THREAD

**Issue by Yuruzu** [YangLin-George/PLELog#5]
hello, I want to use Drain.py  to extract templates for **BGL** dataset but the result is not so good, could you tell me the specific parameter settings？thanks very much

my settings are as follows：

    removeCol = [0, 1, 2, 3, 4, 5, 6, 7, 8]  # [0,1,2,3,4] for HDFS
    st = 0.5
    depth = 4
    rex = [r'core\.\d+']

**Comment by YangLin-George** [comment]
[BGL.zip](https://github.com/YangLin-George/PLELog/files/7567869/BGL.zip)
Hi, 
    Thanks a lot for your question. 
    Here we provide the original BGL parsing code and parsing results as a zip file for research purposes.
    It seems that we were using a rather old version of Drain. To make it easier for coding, please refer to [IBM/Drain3](https://github.com/IBM/Drain3) for the latest version. 

    Thanks again for your question!

**Comment by Yuruzu** [comment]
Thanks!!! I will try it
