### ISSUE TITLE
About Step 4: Download Stanford NLP word embeddings

### ISSUE THREAD

**Issue by Yuruzu** [YangLin-George/PLELog#6]
Sorry to bother you. I want to know in the Step 4, which pre-trained word vectors should I download？Does it depend on my task? I want to do log anomaly detection as well
![image](https://user-images.githubusercontent.com/38316798/147410161-748c2dec-61a2-48d2-b335-f8eeccd0376c.png)

**Comment by YangLin-George** [comment]
Does not matter, as long as the dimensions between the vectors you downloaded, and the input of GRU Network are match.

**Comment by Yuruzu** [comment]
> Does not matter, as long as the dimensions between the vectors you downloaded, and the input of GRU Network are match.

Thank you very much!

**Comment by Yuruzu** [comment]
> Does not matter, as long as the dimensions between the vectors you downloaded, and the input of GRU Network are match.

The generated file **templates_HDFS.vec** or **templates_BGL.vec**  is the final **semantic vectors**?

**Comment by YangLin-George** [comment]
> The generated file **templates_HDFS.vec** or **templates_BGL.vec** is the final **semantic vectors**?

Yes.
